import { Router } from 'express';
import { Client } from 'pg';
import { config } from 'dotenv';
import { transactionDebit , transactionCredit } from "../controllers/transaction-control";
import { checkacc } from "../middleware/check-acc";
import { validateTransaction } from "../middleware/validateTransaction";
config();
const client = new Client(process.env.DB_CONNECT);
client.connect();
const router = Router();
router.post('/:accountnumber/debit',checkacc ,validateTransaction, transactionDebit);
router.post('/:accountnumber/credit',checkacc ,validateTransaction , transactionCredit);
export default router;
